# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  snyk: snyk/snyk@1.1
jobs:
  snyk_security_scan:
    docker:
      - image: cimg/openjdk:11.0.5
    working_directory: /mnt/ramdisk/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - snyk/scan:
          severity-threshold: critical
          additional-arguments: --all-projects -d -- "-s .circleci/circleci.settings.xml"
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0.5

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: /mnt/ramdisk/repo
    resource_class: xlarge
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: "-Xms2048m -Xmx2048m"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn -U de.qaware.maven:go-offline-maven-plugin:1.0.0:resolve-dependencies  -Psonatype-snapshots -s .circleci/circleci.settings.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Override artifact version
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              mvn versions:set -DgenerateBackupPoms=false -DnewVersion=2.0-BRANCH-$CIRCLE_BRANCH-SNAPSHOT
            else
              echo "Currently on master branch, not changing snapshot version"
            fi

      - run: mvn -T 8 deploy -Psonatype-snapshots -s .circleci/circleci.settings.xml

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: java-api-clients/target/datadog-api-client-1.2.0-WHOOP-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: environment-variables
      - snyk_security_scan:
          context: environment-variables